### PR TITLE
add support for pnpm

### PR DESCRIPTION
**Pull request by nwaughachukwuma**
### Summary:

- Add new [has-pnpm](https://www.npmjs.com/package/has-pnpm) package to check if the project uses `pnpm`

### CODE REVIEW

**Comment by chambo-e** [comment]
Hello 👋 

Would it be possible to deploy a new version including this please ? :)

**Comment by chambo-e** [comment]
@andresz1 works like a charm, thanks a lot :)

**Comment by TriStarGod** [comment]
Hi @andresz1 . Anytime I get a pull request, this github action fails with

```
size
Unable to locate executable file: pnpm. Please verify either the file path exists or the file can be found within a directory specified by the PATH environment variable. Also check the file mode to verify the file is executable.
```

for [size](https://github.com/TakitoTech/schemez/blob/main/.github/workflows/size.yml). Do you know what could be causing this error? I also don't know how to check if the file is executable.

**Comment by meduzen** [comment]
> Hi @andresz1 . Anytime I get a pull request, this github action fails with
> 
> ```
> size
> Unable to locate executable file: pnpm. Please verify either the file path exists or the file can be found within a directory specified by the PATH environment variable. Also check the file mode to verify the file is executable.
> ```
> 
> for [size](https://github.com/TakitoTech/schemez/blob/main/.github/workflows/size.yml). Do you know what could be causing this error? I also don't know how to check if the file is executable.

On my side, I had to explicity use `pnpm/action-setup@v2` GitHub Action before size limit in order to be able to use it. In your GitHub action config:

```yml
name: Size limit

on:
  pull_request:
    branches:
      - main
jobs:
  size:
    runs-on: ubuntu-latest
    env:
      CI_JOB_NUMBER: 1
    steps:
      - uses: actions/checkout@v1
      - name: Use pnpm
        uses: pnpm/action-setup@v2
      - name: Use Size limit
        uses: andresz1/size-limit-action@dd31dce7dcc72a041fd3e49abf0502b13fc4ce05 # support for pnpm
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          package_manager: pnpm
```

**Pull request merged**
