### PR TITLE
feature: support customize manager

### PR DESCRIPTION
**Pull request by WynterDing**
In some case, we need customize package manager, such as using yarn workspace, I can't install package in the root directory by yarn, so I want to customize the manager be npm.

image

so I think it should support customize package manager.

### CODE REVIEW

**Comment by andresz1** [comment]
Hi @WynterDing! thank you so much for opening this PR ❤️  the changes LGTM but before I would like to clarify something.
The `hasYarn` function checks if you have a `yarn.lock` file and if so it uses `yarn` and not `npm`. Is this behavior not working for you? I just checked and you have a `yarn.lock` in your project.

Also, I'm not sure if you would want to enable `skip_install` see https://github.com/ant-design/pro-components/pull/65

Thank you again!

**Comment by WynterDing** [comment]
Thanks for your reply,  I know how `hasYarn` works, but it could cause some problem in a yarn workspace project.

emm, I also think it's strange to use npm in yarn project.

Maybe I should change the code to support yarn workspace rather than using npm to instead.

Ignore the `skip_install`, it's just a test.

**Comment by andresz1** [comment]
Hey, @WynterDing thank you for the quick reply. So given:
```
Maybe I should change the code to support yarn workspace rather than using npm to instead.
```
Would that make sense to you instead of adding this option? Your changes are ok but maybe are not needed.

Please let me know what you think! happy to help you 💪

**Comment by WynterDing** [comment]
Thanks, I know what's the problem is, it's nothing to do with the package manager, same issue with #33 . 🤣 

I will close this PR.

**Comment by andresz1** [comment]
Cool @WynterDing! thank you 👍

**Pull request closed without merging**
